#!/usr/bin/env bash

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

echo "===> Check if Zookeeper is healthy ..."
cub zk-ready "$SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL" 20 10 2

echo "===> Check if Kafka is healthy ..."
cub kafka-ready "$SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL" 1 20 10 2 
