#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Mesos DC/OS docker deployments will have HOST and PORT0 
# set for the proxying of the service.  We need to
# make sure that we don't override PORT, which is used
# when setting control-center properties.
#
# DC/OS will set PORT_<port> to the proxy port when
# exposing an internal port via a Docker Bridge network;
# but it also sets PORT and PORT0 for the same values.
# 
# Use those values provide things we know we'll need.

[ -n "${PORT:-}" ] && [ -n "${PORT_9021:-}" ] && [ "$PORT" = "${PORT_9021}" ] &&\
	export PORT=9021 || true

