#!/usr/bin/env bash

# Mesos DC/OS docker deployments will have HOST and PORT0 
# set for the proxying of the service.  We need to
# make sure that we don't override PORT, which is used
# when setting control-center properties.
#
# DC/OS will set PORT_<port> to the proxy port when
# exposing an internal port via a Docker Bridge network;
# but it also sets PORT and PORT0 for the same values.
# 
# Use those values provide things we know we'll need.

[ -n "${PORT:-}" ] && [ -n "${PORT_9021:-}" ] && [ "$PORT" = "${PORT_9021}" ] &&\
	export PORT=9021

