#!/usr/bin/env bash

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

echo "===> Check if Zookeeper is healthy ..."
cub zk-ready "$ZOOKEEPER_CONNECT" 20 10 2

echo "===> Check if Kafka is healthy ..."
cub kafka-ready "$ZOOKEEPER_CONNECT" "${CONTROL_CENTER_REPLICATION_FACTOR}" 20 10 2
