#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

echo "===> Check if Zookeeper is healthy ..."
cub zk-ready "$ZOOKEEPER_CONNECT" 20 10 2

echo "===> Check if Kafka is healthy ..."
cub kafka-ready "$ZOOKEEPER_CONNECT" "${CONTROL_CENTER_REPLICATION_FACTOR}" 20 10 2
