#!/usr/bin/env bash

echo "===> Printing /etc/${COMPONENT}/${COMPONENT}.properties "
cat /etc/${COMPONENT}/${COMPONENT}.properties

echo "===> Launching ${COMPONENT} ... "
# Don't need exec as the command has it.
${COMPONENT}-server-start /etc/${COMPONENT}/${COMPONENT}.properties
