#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Mesos DC/OS docker deployments will have several env variables
# (eg HOST and PORT0) that can be used to initialize our properties.
# 
# Use those values provide things we know we'll need if the core
# KAFKA_REST variables are not otherwise set.
#
# NOTE: always include "|| true" at the end of the "export" to
#       avoid returning an error that will abort the container launch.

[ -n "${HOST:-}" ] && [ -z "${KAFKA_REST_HOST_NAME:-}" ] && \
	export KAFKA_REST_HOST_NAME=$HOST || true 

[ -n "${MESOS_TASK_ID:-}" ] && [ -z "${KAFKA_REST_ID:-}" ] && \
	MESOS_SERVICE=${MESOS_TASK_ID%.*} && MESOS_UUID=${MESOS_TASK_ID##*.} && \
	export KAFKA_REST_ID="${MESOS_SERVICE}.${MESOS_UUID%%-*}" || true 
