#!/usr/bin/env bash
#
# Copyright 2016 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

if [[ -n "${KAFKA_REST_ZOOKEEPER_CONNECT-}" ]]
then
    echo "===> Check if Zookeeper is healthy ..."
    cub zk-ready "$KAFKA_REST_ZOOKEEPER_CONNECT" "${KAFKA_REST_CUB_ZK_TIMEOUT:-40}"
fi

echo "===> Check if Kafka is healthy ..."

if [[ -n "${KAFKA_REST_CLIENT_SECURITY_PROTOCOL-}" ]] && [[ $KAFKA_REST_CLIENT_SECURITY_PROTOCOL != "PLAINTEXT" ]]
then
    cub kafka-ready \
        "${KAFKA_REST_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${KAFKA_REST_CUB_KAFKA_TIMEOUT:-40}" \
        -b "${KAFKA_REST_BOOTSTRAP_SERVERS}" \
        --config /etc/"${COMPONENT}"/admin.properties
else
    if [[ -n "${KAFKA_REST_ZOOKEEPER_CONNECT-}" ]]
    then
        cub kafka-ready \
            "${KAFKA_REST_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${KAFKA_REST_CUB_KAFKA_TIMEOUT:-40}" \
            -z "$KAFKA_REST_ZOOKEEPER_CONNECT"
    elif [[ -n "${KAFKA_REST_BOOTSTRAP_SERVERS-}" ]]
    then
        cub kafka-ready \
            "${KAFKA_REST_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${KAFKA_REST_CUB_KAFKA_TIMEOUT:-40}" \
            -b "${KAFKA_REST_BOOTSTRAP_SERVERS}"
    fi
fi
