#!/usr/bin/env bash

echo "===> Printing /etc/${COMPONENT}/${COMPONENT}.properties "
cat /etc/${COMPONENT}/${COMPONENT}.properties

echo "===> Launching kafka ... "
# Don't need exec as the command has it.
${COMPONENT}-start /etc/${COMPONENT}/${COMPONENT}.properties
