#!/usr/bin/env bash

if [[ -n "${ZOOKEEPER_SERVER_ID-}" ]]
then
  echo "===> Printing /var/lib/${COMPONENT}/data/myid "
  cat /var/lib/"${COMPONENT}"/data/myid
fi

echo "===> Launching ${COMPONENT} ... "
exec "${COMPONENT}"-server-start /etc/kafka/"${COMPONENT}".properties
